# Generated by Django 5.0.3 on 2024-03-26 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('divulgacao', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='midia',
            name='arquivo',
            field=models.FileField(upload_to='divulgacao/midias/'),
        ),
    ]
