# Generated by Django 5.0.3 on 2024-03-26 19:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('divulgacao', '0002_alter_midia_arquivo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='midia',
            name='arquivo',
        ),
        migrations.RemoveField(
            model_name='midia',
            name='tipo',
        ),
        migrations.CreateModel(
            name='ArquivoMidia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo', models.FileField(upload_to='midias/')),
                ('tipo', models.CharField(choices=[('imagem', 'Imagem'), ('video', 'Vídeo')], max_length=10)),
                ('midia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arquivos_midia', to='divulgacao.midia')),
            ],
        ),
    ]
