# Generated by Django 5.0.3 on 2024-03-26 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('divulgacao', '0003_remove_midia_arquivo_remove_midia_tipo_arquivomidia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arquivomidia',
            name='arquivo',
            field=models.FileField(upload_to='divulgacao/midias/'),
        ),
    ]
