# Generated by Django 5.0.3 on 2024-03-26 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('divulgacao', '0004_alter_arquivomidia_arquivo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arquivomidia',
            name='arquivo',
            field=models.FileField(upload_to='midia/'),
        ),
    ]
