# Generated by Django 5.0.3 on 2024-04-04 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('divulgacao', '0005_alter_arquivomidia_arquivo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='arquivomidia',
            options={'verbose_name': ' Cadastrar Imagem/Video', 'verbose_name_plural': ' Cadastrar Imagens/Videos'},
        ),
        migrations.AlterModelOptions(
            name='midia',
            options={'verbose_name': ' Cadastrar TV', 'verbose_name_plural': ' Cadastrar TVs'},
        ),
    ]
