# Generated by Django 5.0.3 on 2024-04-05 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('divulgacao', '0006_alter_arquivomidia_options_alter_midia_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='arquivomidia',
            name='tempo',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
